steps:
  # Dockerイメージビルド - ビルド中に環境変数を渡す
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'asia-northeast1-docker.pkg.dev/specsheet-generator/specsheet-docker/specsheet-generator:latest', 
      '--build-arg', 'NEXT_PUBLIC_FIREBASE_API_KEY=$$NEXT_PUBLIC_FIREBASE_API_KEY',
      '--build-arg', 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$$NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN',
      '--build-arg', 'NEXT_PUBLIC_FIREBASE_PROJECT_ID=$$NEXT_PUBLIC_FIREBASE_PROJECT_ID',
      '--build-arg', 'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$$NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET',
      '--build-arg', 'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$$NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID',
      '--build-arg', 'NEXT_PUBLIC_FIREBASE_APP_ID=$$NEXT_PUBLIC_FIREBASE_APP_ID',
      '--build-arg', 'NEXT_PUBLIC_ALGOLIA_APP_ID=$$NEXT_PUBLIC_ALGOLIA_APP_ID',
      '--build-arg', 'NEXT_PUBLIC_ALGOLIA_SEARCH_API_KEY=$$NEXT_PUBLIC_ALGOLIA_SEARCH_API_KEY',
      '--build-arg', 'ALGOLIA_ADMIN_API_KEY=$$ALGOLIA_ADMIN_API_KEY',
      '--build-arg', 'ALGOLIA_INDEX_NAME=$$ALGOLIA_INDEX_NAME',
      '--build-arg', 'NEXT_PUBLIC_ALGOLIA_INDEX_NAME=$$NEXT_PUBLIC_ALGOLIA_INDEX_NAME',
      '-f', 'Dockerfile', 
      '.'
    ]
    secretEnv: [
      'NEXT_PUBLIC_FIREBASE_API_KEY',
      'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN',
      'NEXT_PUBLIC_FIREBASE_PROJECT_ID',
      'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET',
      'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID',
      'NEXT_PUBLIC_FIREBASE_APP_ID',
      'NEXT_PUBLIC_ALGOLIA_APP_ID',
      'NEXT_PUBLIC_ALGOLIA_SEARCH_API_KEY',
      'ALGOLIA_ADMIN_API_KEY',
      'ALGOLIA_INDEX_NAME',
      'NEXT_PUBLIC_ALGOLIA_INDEX_NAME'
    ]
    
  # イメージのプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-northeast1-docker.pkg.dev/specsheet-generator/specsheet-docker/specsheet-generator:latest']
    
  # Cloud Runへデプロイ
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'specsheet-generator', 
      '--image=asia-northeast1-docker.pkg.dev/specsheet-generator/specsheet-docker/specsheet-generator:latest', 
      '--region=asia-northeast1', 
      '--platform=managed', 
      '--service-account=frontend-sa@specsheet-generator.iam.gserviceaccount.com',
      '--min-instances=1',
      '--allow-unauthenticated',
      '--set-env-vars=ALLOWED_ORIGINS=https://specsheet-generator-503166429433.asia-northeast1.run.app\,http://localhost:3000,NEXT_PUBLIC_FIREBASE_API_KEY=$$NEXT_PUBLIC_FIREBASE_API_KEY,NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$$NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,NEXT_PUBLIC_FIREBASE_PROJECT_ID=$$NEXT_PUBLIC_FIREBASE_PROJECT_ID,NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$$NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$$NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,NEXT_PUBLIC_FIREBASE_APP_ID=$$NEXT_PUBLIC_FIREBASE_APP_ID,NEXT_PUBLIC_ALGOLIA_APP_ID=$$NEXT_PUBLIC_ALGOLIA_APP_ID,NEXT_PUBLIC_ALGOLIA_SEARCH_API_KEY=$$NEXT_PUBLIC_ALGOLIA_SEARCH_API_KEY,NEXT_PUBLIC_ALGOLIA_INDEX_NAME=$$NEXT_PUBLIC_ALGOLIA_INDEX_NAME,ALGOLIA_ADMIN_API_KEY=$$ALGOLIA_ADMIN_API_KEY,ALGOLIA_INDEX_NAME=$$ALGOLIA_INDEX_NAME',
      '--set-secrets=FIREBASE_ADMIN_KEY=FIREBASE_ADMIN_KEY:latest'
    ]
    secretEnv: [
      'NEXT_PUBLIC_FIREBASE_API_KEY',
      'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN',
      'NEXT_PUBLIC_FIREBASE_PROJECT_ID',
      'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET',
      'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID',
      'NEXT_PUBLIC_FIREBASE_APP_ID',
      'NEXT_PUBLIC_ALGOLIA_APP_ID',
      'NEXT_PUBLIC_ALGOLIA_SEARCH_API_KEY',
      'ALGOLIA_ADMIN_API_KEY',
      'ALGOLIA_INDEX_NAME',
      'NEXT_PUBLIC_ALGOLIA_INDEX_NAME'
    ]
  
availableSecrets:
  secretManager:
    - versionName: projects/specsheet-generator/secrets/NEXT_PUBLIC_FIREBASE_API_KEY/versions/latest
      env: 'NEXT_PUBLIC_FIREBASE_API_KEY'
    - versionName: projects/specsheet-generator/secrets/NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN/versions/latest
      env: 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN'
    - versionName: projects/specsheet-generator/secrets/NEXT_PUBLIC_FIREBASE_PROJECT_ID/versions/latest
      env: 'NEXT_PUBLIC_FIREBASE_PROJECT_ID'
    - versionName: projects/specsheet-generator/secrets/NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET/versions/latest
      env: 'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET'
    - versionName: projects/specsheet-generator/secrets/NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID/versions/latest
      env: 'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID'
    - versionName: projects/specsheet-generator/secrets/NEXT_PUBLIC_FIREBASE_APP_ID/versions/latest
      env: 'NEXT_PUBLIC_FIREBASE_APP_ID'
    - versionName: projects/specsheet-generator/secrets/NEXT_PUBLIC_ALGOLIA_APP_ID/versions/latest
      env: 'NEXT_PUBLIC_ALGOLIA_APP_ID'
    - versionName: projects/specsheet-generator/secrets/NEXT_PUBLIC_ALGOLIA_SEARCH_API_KEY/versions/latest
      env: 'NEXT_PUBLIC_ALGOLIA_SEARCH_API_KEY'
    - versionName: projects/specsheet-generator/secrets/ALGOLIA_ADMIN_API_KEY/versions/latest
      env: 'ALGOLIA_ADMIN_API_KEY'
    - versionName: projects/specsheet-generator/secrets/ALGOLIA_INDEX_NAME/versions/latest
      env: 'ALGOLIA_INDEX_NAME'
    - versionName: projects/specsheet-generator/secrets/NEXT_PUBLIC_ALGOLIA_INDEX_NAME/versions/latest
      env: 'NEXT_PUBLIC_ALGOLIA_INDEX_NAME'