name: Deploy to Cloud Run

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Playwright tests
        run: pnpm exec playwright install --with-deps && pnpm test:e2e

      - name: Setup gcloud (Workload Identity)
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: ">= 510.0.0"
          project_id: specsheet-generator

      - name: Submit Cloud Build
        run: |
          gcloud builds submit --config cloudbuild.yaml . 